In [2]:
import numpy as np
arr = np.random.randint(1, 100, size= (10, 5))
print(arr)

[[48 36 96 37 40]
 [63 20 95  6 77]
 [17 28 38 96 69]
 [38 40  7 90  8]
 [78 74 56 11 24]
 [11 37 39 58 71]
 [71 50 94 73 72]
 [55 21 92 76 85]
 [73 53 72 73 15]
 [17 55 72 19 25]]


In [4]:
print(arr.shape)

(10, 5)


In [11]:
b = arr.reshape(5, 10)
print(b)
print(b.shape)
print(b.ndim)

[[48 36 96 37 40 63 20 95  6 77]
 [17 28 38 96 69 38 40  7 90  8]
 [78 74 56 11 24 11 37 39 58 71]
 [71 50 94 73 72 55 21 92 76 85]
 [73 53 72 73 15 17 55 72 19 25]]
(5, 10)
2


In [21]:
# row wise flattning
flat_b = b.flatten()
print(b)
print(b.ndim)
ravel_b = np.ravel(b, order='C')   
print(ravel_b)

[[48 36 96 37 40 63 20 95  6 77]
 [17 28 38 96 69 38 40  7 90  8]
 [78 74 56 11 24 11 37 39 58 71]
 [71 50 94 73 72 55 21 92 76 85]
 [73 53 72 73 15 17 55 72 19 25]]
2
[48 36 96 37 40 63 20 95  6 77 17 28 38 96 69 38 40  7 90  8 78 74 56 11
 24 11 37 39 58 71 71 50 94 73 72 55 21 92 76 85 73 53 72 73 15 17 55 72
 19 25]


In [20]:
# column wise flattning 
ravel_b = np.ravel(b, order='F')
print(ravel_b)


[48 17 78 71 73 36 28 74 50 53 96 38 56 94 72 37 96 11 73 73 40 69 24 72
 15 63 38 11 55 17 20 40 37 21 55 95  7 39 92 72  6 90 58 76 19 77  8 71
 85 25]
