# multiply in list

In [38]:
arr = [1,2,3]
print(arr*5)
arr = [x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


# Multilpy in an numpy array

In [39]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr1 = arr1*5
print(arr1)

[ 5 10 15 20 25]


# NDarray

In [40]:
import numpy as np
# 1D array
arr1 = np.array([1,2,3,4,5], dtype=np.int32)  # work on any iterable like list tuple (not in set{} though)
print(type(arr1))
print(arr1.ndim)  # print dimension
print(arr1)

# 2d array

arr2 = np.array([
#Col 1|2|3|4|5
    [1,2,3,4,5], # row 1
    [6,7,8,9,10],  # row 2
    [11,12,13,14,15] # row 3
])
print(arr2.ndim)
print(arr2)

# 3D array
arr3 = np.array([
    # floor 1
    [
        [1,2,3], 
        [4,5,6]
    ],
    # floor 2
    [
        [7,8,9],
        [10,11,12]
    ],
    # floor 3
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(arr3.ndim)
print(arr3)

<class 'numpy.ndarray'>
1
[1 2 3 4 5]
2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]]]


# Array Attributes

In [41]:
# Dimention
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# Shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)


# data type
print(arr1.dtype)
print(arr2.dtype)

print(arr3.dtype)

# size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(3, 5)
(3, 2, 3)
int32
int64
int64
5
15
18


# nd Array Datatype

In [42]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
arr = np.array([1.2, 5.3, 4.1])
print(arr.dtype)


int64
float64
<U4


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
arr = np.array([1.2, 5.3, 4.1])
print(arr.dtype)