# multiply in list

In [67]:
arr = [1,2,3]
print(arr*5)
arr = [x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


# Multilpy in an numpy array

In [68]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr1 = arr1*5
print(arr1)

[ 5 10 15 20 25]


# NDarray

In [69]:
import numpy as np
# 1D array
arr1 = np.array([1,2,3,4,5], dtype=np.int32)  # work on any iterable like list tuple (not in set{} though)
print(type(arr1))
print("Array 1 Dimantion: ", arr1.ndim)  # print dimension
print(arr1)

# 2d array

arr2 = np.array([
#Col 1|2|3|4|5
    [1,2,3,4,5], # row 1
    [6,7,8,9,10],  # row 2
    [11,12,13,14,15] # row 3
])
print("Array 2 Dimantion: ", arr2.ndim)
print(arr2)

# 3D array
arr3 = np.array([
    # floor 1
    [
        [1,2,3], 
        [4,5,6]
    ],
    # floor 2
    [
        [7,8,9],
        [10,11,12]
    ],
    # floor 3
    [
        [7,8,9],
        [10,11,12]
    ],
    [# floor  4
        [13,14,15],
        [16,17,18]
    ]
])
print("Array 3 Dimantion: ", arr3.ndim)
print(arr3)


arr4 = np.array([
    [
        [  # floor 1
            [1,2,3,4],
            [3,4,5,6]
        ], 
        [  # floor 2
            [2,3,4,5],
            [1,2,3,4],
        ]
    ],
    [
        [  # floor 1
            [1,2,3,4],
            [3,4,5,6]
        ], 
        [  # floor 2
            [2,3,4,5],
            [1,2,3,4],
        ]
    ]
]
    
    
)
print("Array 4 Dimantion: ", arr4.ndim)
print(arr4)


<class 'numpy.ndarray'>
Array 1 Dimantion:  1
[1 2 3 4 5]
Array 2 Dimantion:  2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Array 3 Dimantion:  3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Array 4 Dimantion:  4
[[[[1 2 3 4]
   [3 4 5 6]]

  [[2 3 4 5]
   [1 2 3 4]]]


 [[[1 2 3 4]
   [3 4 5 6]]

  [[2 3 4 5]
   [1 2 3 4]]]]


# Array Attributes

In [70]:
# Dimention
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

# Shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr4.shape)


# data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)

# size
print(arr1.size)
print(arr2.size)
print(arr3.size)
print(arr4.size)

1
2
3
4
(5,)
(3, 5)
(4, 2, 3)
(2, 2, 2, 4)
int32
int64
int64
int64
5
15
24
32


# nd Array Datatype

In [71]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
arr = np.array([1.2, 5.3, 4.1])
print(arr.dtype)


int64
float64


In [72]:
arr = np.array([1,2,3,4,5])
print(arr.dtype) 
arr = np.array([1, 4, 1.2, 2]) #upcasting to float value
print(arr.dtype)

arr = np.array(["Apple", "Banana", "Coconut"])
print(arr.dtype)
arr = np.array([1, 2, '2']) # upcasted to string
print(arr.dtype)


int64
float64
<U7
<U21


## Selecting a datatype for an array and typecasting

In [73]:
arr = np.array([1,2,3,4], dtype=np.int8)
print(arr)
print(arr.dtype)

arr = arr.astype(np.int32)
print(arr.dtype)
arr = np.array([1,2,3,4, "4"])
print(arr)
print(arr.dtype)
arr = arr.astype(np.int32)
print(arr.dtype)

[1 2 3 4]
int8
int32
['1' '2' '3' '4' '4']
<U21
int32


## nd array Creation from existing data

In [74]:
# list
lst = [10, 20, 30, 40, 50, 40.5]
arr = np.array(lst, dtype= np.int32)
print(arr)
print(type(arr))
print(arr.dtype)


mixed_lst = [10, True, "Hello", 10.5]
arr = np.array(mixed_lst)
print(arr)
print(type(arr))
print(arr.dtype)


matrix = [
    [1,2,3],
    [2,3,4]
]

matrix = np.array(matrix)
print(matrix)
print(type(matrix))
print(matrix.dtype)
print(matrix.shape)
print(matrix.ndim)

[10 20 30 40 50 40]
<class 'numpy.ndarray'>
int32
['10' 'True' 'Hello' '10.5']
<class 'numpy.ndarray'>
<U32
[[1 2 3]
 [2 3 4]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [75]:
# tupple
tpl = (10, 20, 30, 40, 50, 40.5)
tpl = np.array(tpl, dtype= np.int32)
print(tpl)
print(type(tpl))
print(tpl.dtype)

[10 20 30 40 50 40]
<class 'numpy.ndarray'>
int32


In [76]:
# set
st = {10, 20, 30, 40, 50}
st = np.array(list(st))
print(st)
print(type(st))
print(st.dtype)
print(st.shape)
print(st.ndim)

[50 20 40 10 30]
<class 'numpy.ndarray'>
int64
(5,)
1


In [77]:
#dictionary
dic = {"a": 10, "b" : 20, "c" : 30}
k = (dic.keys())
v = dic.values()
items = dic.items()
print(k)
print(v)
print(items)

#for keys
arr = np.array(list(k))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

# for values
arr = np.array(list(v), dtype = np.int32)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
# for items
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])
['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
[10 20 30]
<class 'numpy.ndarray'>
int32
(3,)
1
[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
