# ndarray Manipulation 1

In [3]:
import numpy as np
arr = np.random.randint(1, 100, size= (10, 5))
print(arr)

[[28 64 60  8 34]
 [96 86 15 39  8]
 [ 5 39 92 35 94]
 [52 69 45 49 97]
 [46 21 58 93 12]
 [63 52 80 62 36]
 [68 21 84  7 96]
 [45 14 58 92 61]
 [39 16 28 70 52]
 [39 33 54  8 24]]


In [4]:
print(arr.shape)

(10, 5)


In [5]:
b = arr.reshape(5, 10)
print(b)
print(b.shape)
print(b.ndim)

[[28 64 60  8 34 96 86 15 39  8]
 [ 5 39 92 35 94 52 69 45 49 97]
 [46 21 58 93 12 63 52 80 62 36]
 [68 21 84  7 96 45 14 58 92 61]
 [39 16 28 70 52 39 33 54  8 24]]
(5, 10)
2


In [6]:
# row wise flattning
flat_b = b.flatten()
print(b)
print(b.ndim)
ravel_b = np.ravel(b, order='C')   
print(ravel_b)

[[28 64 60  8 34 96 86 15 39  8]
 [ 5 39 92 35 94 52 69 45 49 97]
 [46 21 58 93 12 63 52 80 62 36]
 [68 21 84  7 96 45 14 58 92 61]
 [39 16 28 70 52 39 33 54  8 24]]
2
[28 64 60  8 34 96 86 15 39  8  5 39 92 35 94 52 69 45 49 97 46 21 58 93
 12 63 52 80 62 36 68 21 84  7 96 45 14 58 92 61 39 16 28 70 52 39 33 54
  8 24]


In [7]:
# column wise flattning 
ravel_b = np.ravel(b, order='F')
print(ravel_b)


[28  5 46 68 39 64 39 21 21 16 60 92 58 84 28  8 35 93  7 70 34 94 12 96
 52 96 52 63 45 39 86 69 52 14 33 15 45 80 58 54 39 49 62 92  8  8 97 36
 61 24]


## concat array

In [8]:
a = np.random.randint(1, 10, size= (2,3))
b = np.random.randint(20, 30, size= (2,3))
print(a)
print(b)

[[6 8 2]
 [6 1 2]]
[[20 20 22]
 [26 22 24]]


In [9]:
# row wise  (column need to be same size)
con_row = np.concatenate((a,b), axis = 0)
print(con_row)

[[ 6  8  2]
 [ 6  1  2]
 [20 20 22]
 [26 22 24]]


In [10]:
# column wise (row need to be same size)
con_column = np.concatenate((a,b), axis=1)
print(con_column)

[[ 6  8  2 20 20 22]
 [ 6  1  2 26 22 24]]


In [11]:
# error when the size doesnt macth
a = np.random.randint(1, 10, size= (2,3))
b = np.random.randint(20, 30, size= (1,3))
print(a)
print(b)

[[3 7 9]
 [2 1 4]]
[[23 22 23]]


In [12]:
print(np.concatenate((a,b), axis = 0))
# print(np.concatenate((a,b), axis = 1))  # will show error

[[ 3  7  9]
 [ 2  1  4]
 [23 22 23]]


# ndarray Manipulation 2

In [13]:
# transpose 
mat = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11, 12, 13, 14, 15]
])
tmat = mat.T
print(tmat)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [14]:
# array split
a = np.random.randint(1, 10, size= (18))
print(a)
splitted_array = np.array_split(a, 7) # can be unequal
print(splitted_array)
splitted_array = np.split(a, 2)   # equally devide
print(splitted_array)

[7 7 3 8 9 1 1 2 9 3 9 7 5 6 4 2 4 7]
[array([7, 7, 3], dtype=int32), array([8, 9, 1], dtype=int32), array([1, 2, 9], dtype=int32), array([3, 9, 7], dtype=int32), array([5, 6], dtype=int32), array([4, 2], dtype=int32), array([4, 7], dtype=int32)]
[array([7, 7, 3, 8, 9, 1, 1, 2, 9], dtype=int32), array([3, 9, 7, 5, 6, 4, 2, 4, 7], dtype=int32)]


# ndarray Arithmatic Operation and mathematical function

## arithmatic function and mathematical function

In [15]:
# arithmatic 
x = np.array([10 ,20, 30, 40, 50, 60])
y = np.array([2, 4, 6, 8, 10, 11])
z = np.array([2, 4, 6, 8, 10, 11])
add = x+y+z # add the consecuennt elements of two arrays (arrays need to be in same size)
sub = x-y
mult = x*y*z
div = x/y
mod = x%y
com = x-(y+z)*x
print(add)
print(sub)
print(mult)
print(div)
print(mod)
print(com)



[14 28 42 56 70 82]
[ 8 16 24 32 40 49]
[  40  320 1080 2560 5000 7260]
[5.         5.         5.         5.         5.         5.45454545]
[0 0 0 0 0 5]
[  -30  -140  -330  -600  -950 -1260]


In [16]:
# trigonometric
a = np.sin(np.deg2rad(60)) #for single number the fucntion takes the input in radian 
print(a)

sin_x = np.sin(np.deg2rad(x))
print(sin_x)
cos_y = np.cos(y)
print(cos_y)

0.8660254037844386
[0.17364818 0.34202014 0.5        0.64278761 0.76604444 0.8660254 ]
[-0.41614684 -0.65364362  0.96017029 -0.14550003 -0.83907153  0.0044257 ]


In [17]:
log = np.log10(x) # 10 based log
print(log)
print(np.log2(x))  # 2 based log
print(np.sqrt(x))

[1.         1.30103    1.47712125 1.60205999 1.69897    1.77815125]
[3.32192809 4.32192809 4.9068906  5.32192809 5.64385619 5.9068906 ]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669]


# Numpy Logical Function

In [62]:
# comparison >, <, ==, >=, <=, !=
x = np.array([10 ,20, 30, 40, 50, 60])
y = np.array([2, 40, 6, 8, 50, 11])

greater = x>=y
print(greater)
equal = x==y
print(equal)
print(np.all(x==y))
print(np.any(x==y))

[ 12  60  36  48 100  71]
[ True False  True  True  True  True]
[False False False False  True False]
False
True


# ndarray sort

In [19]:

x = np.array([11,  1, 15,  7, 28, 12, 13, 26, 24, 17,  6, 24])
print(x)

[11  1 15  7 28 12 13 26 24 17  6 24]


In [20]:
# inplace sorting
z = x.copy()
print(z)
z.sort()
print(z)


[11  1 15  7 28 12 13 26 24 17  6 24]
[ 1  6  7 11 12 13 15 17 24 24 26 28]


In [21]:
# copy sort
print(np.sort(x))  
print(x)


[ 1  6  7 11 12 13 15 17 24 24 26 28]
[11  1 15  7 28 12 13 26 24 17  6 24]


In [22]:
# 2d array soritng
mat = np.array([[16, 20, 12, 20],
       [38, 33, 21, 18],
       [37, 12, 25, 35],
       [32, 26, 39, 31]])
print(mat)

[[16 20 12 20]
 [38 33 21 18]
 [37 12 25 35]
 [32 26 39 31]]


In [23]:
print(np.sort(mat, axis=0)) # vertical sort
print(np.sort(mat, axis=1)) # horizontal sort

[[16 12 12 18]
 [32 20 21 20]
 [37 26 25 31]
 [38 33 39 35]]
[[12 16 20 20]
 [18 21 33 38]
 [12 25 35 37]
 [26 31 32 39]]


# Searching

In [24]:
print(x)
print(np.where(x ==12))  # np.where return the indics of the values
print(np.where(x >3)) # np.where return the indics of the values

# np.where(condition, x, y) if true it be x else it will be y
print(np.where(x>12, x, 0)) # here if x>12 it will remain x else turn into 0
print(x)

[11  1 15  7 28 12 13 26 24 17  6 24]
(array([5]),)
(array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),)
[ 0  0 15  0 28  0 13 26 24 17  0 24]
[11  1 15  7 28 12 13 26 24 17  6 24]


In [25]:
# 2d searching
print(mat)
print(np.where(mat < 16))
print((np.where(mat < 16, "Failed", "Passed")))

[[16 20 12 20]
 [38 33 21 18]
 [37 12 25 35]
 [32 26 39 31]]
(array([0, 2]), array([2, 1]))
[['Passed' 'Passed' 'Failed' 'Passed']
 ['Passed' 'Passed' 'Passed' 'Passed']
 ['Passed' 'Failed' 'Passed' 'Passed']
 ['Passed' 'Passed' 'Passed' 'Passed']]


In [35]:
# min max
print(x)
print(np.argmax(x))
print(np.argmin(x))

[11  1 15  7 28 12 13 26 24 17  6 24]
4
1


# Counting 

In [27]:
a = np.random.randint(50, 100, size= (100))
print(a)

[64 66 95 78 76 60 92 72 83 77 91 50 98 92 97 58 68 61 66 59 65 87 90 62
 60 97 85 61 71 52 93 67 71 95 91 97 54 87 89 88 80 92 63 68 98 50 74 88
 63 84 89 88 56 64 98 61 65 73 96 66 99 68 75 76 85 55 52 91 85 61 86 88
 66 69 67 92 53 90 96 97 59 63 60 98 75 97 90 88 75 81 80 90 87 59 91 95
 70 82 78 73]


In [28]:
cnt = np.count_nonzero(a>76)
print(cnt)
cnt = np.count_nonzero(a==61)
print(cnt)
cnt = np.count_nonzero(a<68)

print(cnt)

51
4
33


In [29]:
print(np.unique(a)) #print unique values
unq_val, unq_cnt = np.unique(a, return_counts=True) # return unique values and 
print(unq_val)
print(unq_cnt)

[50 52 53 54 55 56 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75
 76 77 78 80 81 82 83 84 85 86 87 88 89 90 91 92 93 95 96 97 98 99]
[50 52 53 54 55 56 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75
 76 77 78 80 81 82 83 84 85 86 87 88 89 90 91 92 93 95 96 97 98 99]
[2 2 1 1 1 1 1 3 3 4 1 3 2 2 4 2 3 1 1 2 1 2 1 3 2 1 2 2 1 1 1 1 3 1 3 5 2
 4 4 4 1 3 2 5 4 1]


# Stastical Function

In [32]:
# data Load
data = np.genfromtxt('student_marks_50.csv', delimiter=',', skip_header=1)
data


array([[ 49.,  38.,  70.],
       [ 66.,  63.,  52.],
       [ 48.,  46.,  89.],
       [ 39.,  38.,  46.],
       [ 62.,  64.,  99.],
       [ 38.,  60.,  88.],
       [ 63.,  92.,  70.],
       [ 35.,  55.,  89.],
       [ 78.,  70.,  54.],
       [ 62.,  78.,  48.],
       [ 46.,  83.,  47.],
       [ 80.,  79.,  68.],
       [ 40.,  93.,  50.],
       [ 83.,  45.,  72.],
       [ 81.,  59.,  43.],
       [ 40.,  64.,  72.],
       [ 45.,  64.,  47.],
       [ 83.,  70.,  93.],
       [ 81.,  55.,  82.],
       [ 80.,  61.,  69.],
       [ 44.,  56.,  66.],
       [ 55.,  94.,  83.],
       [ 69.,  63.,  76.],
       [ 42.,  64.,  39.],
       [ 75.,  86.,  69.],
       [ 43.,  62.,  75.],
       [ 62.,  98.,  85.],
       [ 93.,  53.,  68.],
       [ 52.,  66.,  68.],
       [ 89.,  86.,  81.],
       [ 63.,  52., 100.],
       [ 98.,  46.,  41.],
       [ 49.,  54.,  55.],
       [ 89.,  43.,  84.],
       [ 83.,  94.,  67.],
       [ 36.,  49.,  69.],
       [ 78.,  49.,  72.],
 

In [45]:
math_marks = data[::, 0:1]
print(math_marks.T)
mx_math_marks = np.max(math_marks)
print(mx_math_marks)
mn_math_marks = np.min(math_marks)
print(mn_math_marks)
median_math_marks = np.median(math_marks)
print(median_math_marks)
std_math_marks = np.std(math_marks)
print(std_math_marks)

[[49. 66. 48. 39. 62. 38. 63. 35. 78. 62. 46. 80. 40. 83. 81. 40. 45. 83.
  81. 80. 44. 55. 69. 42. 75. 43. 62. 93. 52. 89. 63. 98. 49. 89. 83. 36.
  78. 90. 35. 57. 73. 54. 35. 37. 74. 65. 97. 51. 68. 60.]]
98.0
35.0
62.0
18.739530410338464


## correlation

In [49]:
study_hour = np.array([2,3,4,5,6,7])
final_marks = np.array([50,60,70, 75, 80, 90])
data = np.array([study_hour, final_marks])
print(data)
cor = np.corrcoef(data)
print(cor)

[[ 2  3  4  5  6  7]
 [50 60 70 75 80 90]]
[[1.        0.9913327]
 [0.9913327 1.       ]]


# Linear Algebra

In [58]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.array([
    [2,3],
    [7,8],
    [4, 9]
])
sq = np.array([
    [1,2,3],
    [2,3,4],
    [4,5,6]
])
dot_product = np.dot(a,b)
print(dot_product)
print(np.trace(sq))

# derterminant
print(np.linalg.det(sq))
# rank
print(np.linalg.matrix_rank(sq))

[[ 28  46]
 [ 67 106]]
10
1.665334536937729e-16
2


In [61]:
print(np.sin(np.pi/2))

1.0
