# multiply in list

In [114]:
arr = [1,2,3]
print(arr*5)
arr = [x*5 for x in arr] 
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


# Multilpy in an numpy array

In [115]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr1 = arr1*5
print(arr1)

[ 5 10 15 20 25]


# NDarray

In [116]:
import numpy as np
# 1D array
arr1 = np.array([1,2,3,4,5], dtype=np.int32)  # work on any iterable like list tuple (not in set{} though)
print(type(arr1))
print("Array 1 Dimantion: ", arr1.ndim)  # print dimension
print(arr1)

# 2d array

arr2 = np.array([
#Col 1|2|3|4|5
    [1,2,3,4,5], # row 1
    [6,7,8,9,10],  # row 2
    [11,12,13,14,15] # row 3
])
print("Array 2 Dimantion: ", arr2.ndim)
print(arr2)

# 3D array
arr3 = np.array([
    # floor 1
    [
        [1,2,3], 
        [4,5,6]
    ],
    # floor 2
    [
        [7,8,9],
        [10,11,12]
    ],
    # floor 3
    [
        [7,8,9],
        [10,11,12]
    ],
    [# floor  4
        [13,14,15],
        [16,17,18]
    ]
])
print("Array 3 Dimantion: ", arr3.ndim)
print(arr3)


arr4 = np.array([
    [
        [  # floor 1
            [1,2,3,4],
            [3,4,5,6]
        ], 
        [  # floor 2
            [2,3,4,5],
            [1,2,3,4],
        ]
    ],
    [
        [  # floor 1
            [1,2,3,4],
            [3,4,5,6]
        ], 
        [  # floor 2
            [2,3,4,5],
            [1,2,3,4],
        ]
    ]
]
    
    
)
print("Array 4 Dimantion: ", arr4.ndim)
print(arr4)


<class 'numpy.ndarray'>
Array 1 Dimantion:  1
[1 2 3 4 5]
Array 2 Dimantion:  2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Array 3 Dimantion:  3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Array 4 Dimantion:  4
[[[[1 2 3 4]
   [3 4 5 6]]

  [[2 3 4 5]
   [1 2 3 4]]]


 [[[1 2 3 4]
   [3 4 5 6]]

  [[2 3 4 5]
   [1 2 3 4]]]]


# Array Attributes

In [117]:
# Dimention
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

# Shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr4.shape)


# data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)

# size
print(arr1.size)
print(arr2.size)
print(arr3.size)
print(arr4.size)

1
2
3
4
(5,)
(3, 5)
(4, 2, 3)
(2, 2, 2, 4)
int32
int64
int64
int64
5
15
24
32


# nd Array Datatype

In [118]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
arr = np.array([1.2, 5.3, 4.1])
print(arr.dtype)


int64
float64


In [119]:
arr = np.array([1,2,3,4,5])
print(arr.dtype) 
arr = np.array([1, 4, 1.2, 2]) #upcasting to float value
print(arr.dtype)

arr = np.array(["Apple", "Banana", "Coconut"])
print(arr.dtype)
arr = np.array([1, 2, '2']) # upcasted to string
print(arr.dtype)


int64
float64
<U7
<U21


## Selecting a datatype for an array and typecasting

In [120]:
arr = np.array([1,2,3,4], dtype=np.int8)
print(arr)
print(arr.dtype)

arr = arr.astype(np.int32)
print(arr.dtype)
arr = np.array([1,2,3,4, "4"])
print(arr)
print(arr.dtype)
arr = arr.astype(np.int32)
print(arr.dtype)

[1 2 3 4]
int8
int32
['1' '2' '3' '4' '4']
<U21
int32


## nd array Creation from existing data

In [121]:
# list
lst = [10, 20, 30, 40, 50, 40.5]
arr = np.array(lst, dtype= np.int32)
print(arr)
print(type(arr))
print(arr.dtype)


mixed_lst = [10, True, "Hello", 10.5]
arr = np.array(mixed_lst)
print(arr)
print(type(arr))
print(arr.dtype)


matrix = [
    [1,2,3],
    [2,3,4]
]

matrix = np.array(matrix)
print(matrix)
print(type(matrix))
print(matrix.dtype)
print(matrix.shape)
print(matrix.ndim)

[10 20 30 40 50 40]
<class 'numpy.ndarray'>
int32
['10' 'True' 'Hello' '10.5']
<class 'numpy.ndarray'>
<U32
[[1 2 3]
 [2 3 4]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [122]:
# tupple
tpl = (10, 20, 30, 40, 50, 40.5)
tpl = np.array(tpl, dtype= np.int32)
print(tpl)
print(type(tpl))
print(tpl.dtype)

[10 20 30 40 50 40]
<class 'numpy.ndarray'>
int32


In [123]:
# set
st = {10, 20, 30, 40, 50}
st = np.array(list(st))
print(st)
print(type(st))
print(st.dtype)
print(st.shape)
print(st.ndim)

[50 20 40 10 30]
<class 'numpy.ndarray'>
int64
(5,)
1


In [124]:
#dictionary
dic = {"a": 10, "b" : 20, "c" : 30}
k = (dic.keys())
v = dic.values()
items = dic.items()
print(k)
print(v)
print(items)

#for keys
arr = np.array(list(k))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

# for values
arr = np.array(list(v), dtype = np.int32)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
# for items
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])
['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
[10 20 30]
<class 'numpy.ndarray'>
int32
(3,)
1
[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2


# Array Creation with random values

### Random 

In [125]:
# np.random.rand(shape)
import numpy as np
# arr = np.random.rand(3)   # create a 1d array of random floating number
arr = np.random.rand(3,4)   # create a 2d array of random floating number
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.33594831 0.21112354 0.12979358 0.18337824]
 [0.35672549 0.25873511 0.49935261 0.88626045]
 [0.25478921 0.35135649 0.26791748 0.35459991]]
<class 'numpy.ndarray'>
float64
(3, 4)
2
12


### Random Integer

In [126]:
# np.random.randint(startpoint, endpoint, shape)
import numpy as np
# arr = np.random.randint(1, 10, (3,4))   # create a 1d array of random integer number (must define the range (1-10))
arr = np.random.randint(1, 100, (10,10))   # create a 2d array of random integer number (must define the range (1-10))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[25 99 59 50 30 99 38 66 11  7]
 [27 88 62 56 75 75 13 53 11 57]
 [74 76 30 72 98 83 57 31 11 48]
 [38 74 62  7 27 14  7 42 20 30]
 [37 93 57 72 24 87 39 83 93 95]
 [54 52 94 33 71 28 92 71 58 85]
 [64 75 64 38 52  1 81 35 55 95]
 [91 52  8 35 37 34 22 16 25 62]
 [58 29 12 34 96  7 14 78 73 98]
 [42 45 58 69 44 13 94 57 29 16]]
<class 'numpy.ndarray'>
int32
(10, 10)
2
100


### uniform / float

In [127]:
# np.random.uniform(startpoint, endpoint, shape)
import numpy as np
# arr = np.random.unifor(1, 10, (3,4))   # create a 1d array of random integer number (must define the range (1-10))
arr = np.random.uniform(1, 100, (10,10))   # create a 2d array of random integer number (must define the range (1-10))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[89.70488559 66.67007287 56.32856902 25.59933984 54.26171158 70.3304465
  92.72933327 86.36832715 31.51551954 83.15136208]
 [99.4093719  82.45508226 94.82849888 19.40485838 41.97165127 89.25829731
  32.31832948 25.61224754 80.27876116 11.86220104]
 [47.492184   18.54349071 56.11921434 25.19379865 62.68842425 33.50699004
  80.49564481  4.59796797 50.55542415 36.67706798]
 [63.05433278 60.90036827 60.8069736  49.77254243 48.66642584 52.25438473
   7.69217982 89.29121451  3.67316188 64.78777   ]
 [36.37451958 49.52842732 71.46665587 46.82622995 39.94148187 47.33628756
  38.31213662 27.25069846 37.72380839 89.04919968]
 [66.74649608 79.70274176 14.89027567  3.31280321 24.50152394 38.22435353
  97.61502504 46.46530748 78.14236224 93.86224101]
 [22.08920773 52.09064472 29.6751779  83.71835743 67.38015407 72.7656257
  57.68449479 25.56616976 72.20098853  1.60401971]
 [ 1.34792995 45.7307676  19.61986256 66.66259583 70.05540319 91.58814779
  81.36175864 37.60635641 38.22600512 60.58638036]
 [

### array creation with range function

In [128]:
# np.arange(first, end, step) -> smilar to range function
# np.arange(first, end, step).reshape(x,y) -> to turn into matrix
arr = np.arange(1, 101, 1)
arr = arr.reshape(5,20)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20]
 [ 21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
   39  40]
 [ 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
   59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
   79  80]
 [ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
   99 100]]
<class 'numpy.ndarray'>
int64
(5, 20)
2
100


In [129]:
# np.linspace(start, end(included), koyta)
arr = np.linspace(1, 1000, 11)   # pic the number of point in the range
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[   1.   100.9  200.8  300.7  400.6  500.5  600.4  700.3  800.2  900.1
 1000. ]
<class 'numpy.ndarray'>
float64
(11,)
1
11


In [132]:
# np.logspace(start, end(included), number of points, base(default 10))
arr = np.logspace(0, 4, 6, base=3)   # here start and end point is base power the point lione base^0 and base^4
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.          2.40822469  5.79954613 13.96661017 33.63473537 81.        ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


# Indexing and slicing

In [139]:
#indexing
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([
#Col 1|2|3|4|5
    [1,2,3,4,5], # row 1
    [6,7,8,9,10],  # row 2
    [11,12,13,14,15] # row 3
])
print(arr1)
print(arr2)
print(arr1[2])
arr1[2] = 100
print(arr1)

print(arr2[1][2])

arr2[2][4]=100
print(arr2)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
3
[  1   2 100   4   5]
8
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14 100]]


In [161]:
# slicing
# 1d slicing
arr_mod = arr1[1:4]
print(arr_mod)

# 2d slicing
# arr[row_start : row_end : step , column_start : column_end :step]

print(arr2)
# getting a row
row_0 = arr2[0:1, ]
row_next = arr2[1:2]
print(row_0)
print(row_next)
# getting a column
column_0 = arr2[::, 0:1]
column_0 = arr2[::, 1:]
print(column_0)

[  2 100   4]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14 100]]
[[1 2 3 4 5]]
[[ 6  7  8  9 10]]
[[  2   3   4   5]
 [  7   8   9  10]
 [ 12  13  14 100]]


# Ndarray Copy Advanced Indexing and Iteration

In [167]:
arr1 = np.array([1,2,3,4,5])
arr_mod = arr1[1:4]
print(arr1)
arr_mod[1]=7
print(arr1)    # change in a sliced array will efect the main array because it a view not copy
print(arr_mod)


[1 2 3 4 5]
[1 2 7 4 5]
[2 7 4]


In [168]:
#copy sliced array
arr1 = np.array([1,2,3,4,5])
arr_mod = arr1[1:4].copy()
print(arr1)
arr_mod[1]=7
print(arr1)    # change in a sliced array will efect the main array because it a view not copy
print(arr_mod)

[1 2 3 4 5]
[1 2 3 4 5]
[2 7 4]
