# ndarray Manipulation 1

In [3]:
import numpy as np
arr = np.random.randint(1, 100, size= (10, 5))
print(arr)

[[ 5 27 13 80 51]
 [31 73 32 95 31]
 [68 41 28 96 14]
 [ 2 87 31 35 54]
 [35 64 94 90 86]
 [47 79 95 71 15]
 [82  4 91 31 87]
 [14 25 93 93 87]
 [64 52 15 83 48]
 [39 79 56 38 29]]


In [4]:
print(arr.shape)

(10, 5)


In [5]:
b = arr.reshape(5, 10)
print(b)
print(b.shape)
print(b.ndim)

[[ 5 27 13 80 51 31 73 32 95 31]
 [68 41 28 96 14  2 87 31 35 54]
 [35 64 94 90 86 47 79 95 71 15]
 [82  4 91 31 87 14 25 93 93 87]
 [64 52 15 83 48 39 79 56 38 29]]
(5, 10)
2


In [6]:
# row wise flattning
flat_b = b.flatten()
print(b)
print(b.ndim)
ravel_b = np.ravel(b, order='C')   
print(ravel_b)

[[ 5 27 13 80 51 31 73 32 95 31]
 [68 41 28 96 14  2 87 31 35 54]
 [35 64 94 90 86 47 79 95 71 15]
 [82  4 91 31 87 14 25 93 93 87]
 [64 52 15 83 48 39 79 56 38 29]]
2
[ 5 27 13 80 51 31 73 32 95 31 68 41 28 96 14  2 87 31 35 54 35 64 94 90
 86 47 79 95 71 15 82  4 91 31 87 14 25 93 93 87 64 52 15 83 48 39 79 56
 38 29]


In [7]:
# column wise flattning 
ravel_b = np.ravel(b, order='F')
print(ravel_b)


[ 5 68 35 82 64 27 41 64  4 52 13 28 94 91 15 80 96 90 31 83 51 14 86 87
 48 31  2 47 14 39 73 87 79 25 79 32 31 95 93 56 95 35 71 93 38 31 54 15
 87 29]


## concat array

In [8]:
a = np.random.randint(1, 10, size= (2,3))
b = np.random.randint(20, 30, size= (2,3))
print(a)
print(b)

[[6 6 5]
 [9 1 1]]
[[23 23 27]
 [25 27 29]]


In [16]:
# row wise  (column need to be same size)
con_row = np.concatenate((a,b), axis = 0)
print(con_row)

[[ 6  6  5]
 [ 9  1  1]
 [23 23 27]
 [25 27 29]]


In [15]:
# column wise (row need to be same size)
con_column = np.concatenate((a,b), axis=1)
print(con_column)

[[ 6  6  5 23 23 27]
 [ 9  1  1 25 27 29]]


In [17]:
# error when the size doesnt macth
a = np.random.randint(1, 10, size= (2,3))
b = np.random.randint(20, 30, size= (1,3))
print(a)
print(b)

[[2 8 8]
 [7 1 7]]
[[23 24 27]]


In [18]:
print(np.concatenate((a,b), axis = 0))
# print(np.concatenate((a,b), axis = 1))  # will show error

[[ 2  8  8]
 [ 7  1  7]
 [23 24 27]]


# ndarray Manipulation 2

In [23]:
# transpose 
mat = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11, 12, 13, 14, 15]
])
tmat = mat.T
print(tmat)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [36]:
# array split
a = np.random.randint(1, 10, size= (18))
print(a)
splitted_array = np.array_split(a, 7) # can be unequal
print(splitted_array)
splitted_array = np.split(a, 2)   # equally devide
print(splitted_array)

[5 9 8 7 7 6 9 1 9 6 3 1 8 2 6 4 5 1]
[array([5, 9, 8], dtype=int32), array([7, 7, 6], dtype=int32), array([9, 1, 9], dtype=int32), array([6, 3, 1], dtype=int32), array([8, 2], dtype=int32), array([6, 4], dtype=int32), array([5, 1], dtype=int32)]
[array([5, 9, 8, 7, 7, 6, 9, 1, 9], dtype=int32), array([6, 3, 1, 8, 2, 6, 4, 5, 1], dtype=int32)]


# ndarray Arithmatic Operation and mathematical function

## arithmatic function and mathematical function